"""create payments

Revision ID: 29e3a0248d76
Revises: eee39b432e07
Create Date: 2026-10-04 23:42:45.223671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e3a0248d76'
down_revision: Union[str, Sequence[str], None] = 'eee39b432e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rent_charge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('card', 'bank_transfer', 'cash')", name='ck_payments_method'),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['rent_charge_id'], ['rent_charges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_payments_user_key')
    )
    op.create_index(op.f('ix_payments_rent_charge_id'), 'payments', ['rent_charge_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_rent_charge_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
