"""add reminder_sent_at to rent charges

Revision ID: 3e60fa4a7d24
Revises: 29e3a0248d76
Create Date: 2026-10-05 00:17:50.776120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e60fa4a7d24'
down_revision: Union[str, Sequence[str], None] = '29e3a0248d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rent_charges', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rent_charges', 'reminder_sent_at')
    # ### end Alembic commands ###
