"""create maintenance requests

Revision ID: 89235cb6b273
Revises: 3e60fa4a7d24
Create Date: 2026-10-05 00:32:51.886638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89235cb6b273'
down_revision: Union[str, Sequence[str], None] = '3e60fa4a7d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='submitted', nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("category IN ('plumbing', 'electrical', 'heating', 'appliance', 'structural', 'other')", name='ck_maintenance_category'),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'urgent')", name='ck_maintenance_priority'),
    sa.CheckConstraint("status IN ('submitted', 'assigned', 'in_progress', 'resolved')", name='ck_maintenance_status'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_requests_reported_by'), 'maintenance_requests', ['reported_by'], unique=False)
    op.create_index('ix_maintenance_unit_status', 'maintenance_requests', ['unit_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_maintenance_unit_status', table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_reported_by'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    # ### end Alembic commands ###
