"""create leases and rent charges

Revision ID: de74759a0bd9
Revises: 2e8fecdd25cb
Create Date: 2026-10-04 20:43:55.225791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de74759a0bd9'
down_revision: Union[str, Sequence[str], None] = '2e8fecdd25cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('rent_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'ended', 'cancelled')", name='ck_leases_status'),
    sa.CheckConstraint('due_day BETWEEN 1 AND 28', name='ck_leases_due_day'),
    sa.CheckConstraint('end_date > start_date', name='ck_leases_dates'),
    sa.CheckConstraint('rent_amount > 0', name='ck_leases_rent_positive'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leases_tenant_id'), 'leases', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_leases_unit_id'), 'leases', ['unit_id'], unique=False)
    op.create_table('rent_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.CheckConstraint("status IN ('pending', 'partial', 'paid', 'overdue')", name='ck_rent_charges_status'),
    sa.CheckConstraint('amount > 0', name='ck_rent_charges_amount_positive'),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lease_id', 'due_date', name='uq_rent_charges_lease_due')
    )
    op.create_index('ix_rent_charges_due_status', 'rent_charges', ['due_date', 'status'], unique=False)
    op.create_index(op.f('ix_rent_charges_lease_id'), 'rent_charges', ['lease_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rent_charges_lease_id'), table_name='rent_charges')
    op.drop_index('ix_rent_charges_due_status', table_name='rent_charges')
    op.drop_table('rent_charges')
    op.drop_index(op.f('ix_leases_unit_id'), table_name='leases')
    op.drop_index(op.f('ix_leases_tenant_id'), table_name='leases')
    op.drop_table('leases')
    # ### end Alembic commands ###
